### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by H4ckBu7eer-EX** [Metick/DMALibrary#10] opened 2024-03-08 00:29 UTC
Recalling mem. init failed to initialize when restarting the exe to be read

**Comment by H4ckBu7eer-EX** [comment] 2024-03-08 00:30
I'll upload my source code in a moment

**Comment by H4ckBu7eer-EX** [comment] 2024-03-08 04:35
Added in Memory.cpp

```
bool Memory::ResetDMA()
{
	DMA_INITIALIZED = false;
	PROCESS_INITIALIZED = false;
	return true;
}

bool Memory::ResetProcess()
{
	PROCESS_INITIALIZED = false;
	return true;
}
```

Main.cpp
```
void Init() {
	while (true) {
		Offset::UpdateOffsets();
		if (!mem.Init("edge.exe") || !gGame.InitAddress()) {
			LOG("[ERROR] Mem Initialize ERROR\n");
			config.init = false;
			mem.ResetDMA();
		}
		else {
			if (mem.GetPidFromName("edge.exe") != 0) {
				config.init = true;
			}
			else {
				config.init = false;
				mem.ResetDMA();
				mem.ResetProcess();
			}
		}
		Sleep(7000);
	}
}

CreateThread(nullptr, 0, (LPTHREAD_START_ROUTINE)(Init), NULL, 0, 0);
```

CMD
```
[+] Found Base Address for client.dll at 0x00007FF97C7A0000
DMA already initialized!
Process already initialized!
[+] Found Base Address for client.dll at 0x00007FF97C7A0000
DMA already initialized!
Process already initialized!
[+] Found Base Address for client.dll at 0x00007FF97C7A0000
inizializing...
dumping memory map to file...
Dumped memory map!
[!] Initialization failed with Memory map? Try without MMap
[!] Initialization failed! Is the DMA in use or disconnected?
[ERROR] Mem Initialize ERROR
inizializing...
dumping memory map to file...
Dump
```

Perhaps a Reinit() function should be added to reinitialize the DMA device handle and re-fixcr3.

**Comment by Metick** [comment] 2024-03-08 17:02
I don't really understand what's wrong? you're only supposed to intiailize the process once, which you do at the start. If the target process closes, then you'll have to clear PROCESS_INITIALIZED, which you're already doing. but if you wanna reset DMA you'll have to do this:

```
void Memory::CloseMemory()
{
	VMMDLL_Close(this->vHandle);
	DMA_INITIALIZED = false;
	PROCESS_INITIALIZED = false;
}
```

You can't open another VMM handle without closing it first.

**Comment by H4ckBu7eer-EX** [comment] 2024-03-08 22:59
Thanks, I'll try it

**Comment by Metick** [comment] 2024-03-09 12:01
Did you get it working?

**Comment by H4ckBu7eer-EX** [comment] 2024-03-09 16:02
In fact, no, every time I close the game and turn it on, I need to restart the cheat, I tried to write the function myself to detect that the game is running and initialize the cheat , but it doesn't work

**Comment by H4ckBu7eer-EX** [comment] 2024-03-09 16:02
Sorry for my English, I'm a Google Translate user

**Comment by H4ckBu7eer-EX** [comment] 2024-03-09 16:31
When I call mem.getpidfromname outside the mem.init function, pid always returns 0 (DMA has been initialized)

**Comment by Metick** [comment] 2024-03-09 21:05
You're either doing something wrong in code, or the DMA is not initialized. This is not a bug or issue related to the library. I've provided a example above that can be used to close handle to DMA + set dma & process initialized to false. anything else you'll have to fix in your own codebase that allows for a reinitialization of the process correctly.

I'll be closing the Issue as it isn't a issue or bug with the library.

**Closed as completed by Metick** 2024-03-09 21:05 UTC
