### ISSUE TITLE
Fixed cr3 display successfully but module DLL still couldn't get base address

### ISSUE THREAD

**Issue by lxwcv** [Metick/DMALibrary#25] opened 2024-08-06 14:26 UTC
Fixed cr3 display successfully but module DLL still couldn't get base address

**Comment by lxwcv** [comment] 2024-08-06 14:26
How to solve

**Comment by Metick** [comment] 2024-08-06 20:15
I don't know without knowing exactly what you're doing

**Comment by subeoy1** [comment] 2024-08-08 15:35
> I don't know without knowing exactly what you're doing

Due to the game update two days ago, your CR3 decryption is outdated and the game has fixed it

**Comment by Metick** [comment] 2024-08-09 12:01
> > I don't know without knowing exactly what you're doing
> 
> Due to the game update two days ago, your CR3 decryption is outdated and the game has fixed it

It still works fine on how i do it on my private version of the library. Which is similiar to the public one. I'm sure with a slight change you can make it work again, if it even is broken (i doubt it)

**Comment by subeoy1** [comment] 2024-08-09 13:11
> > > I don't know without knowing exactly what you're doing
> > 
> > 
> > Due to the game update two days ago, your CR3 decryption is outdated and the game has fixed it
> 
> It still works fine on how i do it on my private version of the library. Which is similiar to the public one. I'm sure with a slight change you can make it work again, if it even is broken (i doubt it)

You really overestimate me, I can't resist kneeling down and begging you to update!

**Comment by Metick** [comment] 2024-08-09 13:34
> > > > I don't know without knowing exactly what you're doing
> > > 
> > > 
> > > Due to the game update two days ago, your CR3 decryption is outdated and the game has fixed it
> > 
> > 
> > It still works fine on how i do it on my private version of the library. Which is similiar to the public one. I'm sure with a slight change you can make it work again, if it even is broken (i doubt it)
> 
> You really overestimate me, I can't resist kneeling down and begging you to update!

Are you able to do mem.GetBaseDaddy("Executable"); ? after you fix cr3

**Comment by subeoy1** [comment] 2024-08-09 13:49
> GetBaseDaddy

It's not an issue with GetBaseDaddy

But it's CR3 ↓

He will get stuck in ↓
while (true)
{
BYTE bytes[4] = { 0 };
DWORD i = 0;
auto nt = VMMDLL_VfsReadW(MEM::vmm_handle, const_cast<LPWSTR>(L"\\misc\\procinfo\\progress_percent.txt"), bytes, 3, &i, 0);
if (nt == VMMDLL_STATUS_SUCCESS && atoi(reinterpret_cast<LPSTR>(bytes)) == 100)
break;

std::this_thread::sleep_for(std::chrono::milliseconds(100));
}

---------------Although I passed the above

however
while (std::getline(iss, line))
{
Info info = { };

std::istringstream info_ss(line);
if (info_ss >> std::hex >> info.index >> std::dec >> info.process_id >> std::hex >> info.dtb >> info.kernelAddr >> info.name)
{
if (info.process_id == 0) //parts that lack a name or have a NULL pid are suspects
possible_dtbs.push_back(info.dtb);
if (client11().find(info.name) !=  std::string::npos)
possible_dtbs.push_back(info.dtb);
}
} 
It's stuck here again, and I let him pass through
----------------

for (size_t i = 0;  i < possible_dtbs.size();  i++)
{
auto dtb = possible_dtbs[i];
VMMDLL_ConfigSet(this->vmm_handle,  VMMDLL_OPT_PROCESS_DTB | this->PID, dtb);
result = VMMDLL_Map_GetModuleFromNameU(this->vmm_handle, this->PID, const_cast<LPSTR>(client11().c_str()), &module_entry, NULL);
if (result)
{
//printWithTimestamp1("[+] Initialize succed！\n");
return true;
}
}

It returns normally here, but it's an old DTB cache. I updated the cache, but I can't do anything about it

I suspect that the game detected these TXT files. You can make it a memory read
But I don't have any ideas, so I'm begging you!

**Comment by Metick** [comment] 2024-08-09 13:55
CR3 didn't get patched, your issue is it's not loading the VMM plugin.

**Comment by subeoy1** [comment] 2024-08-09 14:09
VMMDLL_CloseAll(); and  VMMDLL_MemFree(this->vmm_handle);

I call it every time! Before the next reinitialization! Because yesterday after the CS2 battle platform update, the second one will be like this. I suspect that a large amount of garbage was put in it

**Comment by subeoy1** [comment] 2024-08-09 14:28
> CR3 didn't get patched, your issue is it's not loading the VMM plugin.

	while (std::getline(iss, line))
	{
		Info info = { };

		std::istringstream info_ss(line);
		if (info_ss >> std::hex >> info.index >> std::dec >> info.process_id >> std::hex >> info.dtb >> info.kernelAddr >> info.name)
		{
			if (info.process_id == 0) //parts that lack a name or have a NULL pid are suspects
				possible_dtbs.push_back(info.dtb);
			if (client11().find(info.name) != std::string::npos)
				possible_dtbs.push_back(info.dtb);
		}
	}

I have basically confirmed that the problem lies in the information On DTB

**Comment by subeoy1** [comment] 2024-08-09 14:46
I know the problem now, please close this issue directly. Thank you! Just replace it with memory reading. I'll use VMMLL_readEX instead

**Closed as completed** 2024-08-09 14:50 UTC

**Comment by lxwcv** [comment] 2024-08-09 15:29
Brother, how did you solve it?

**Comment by lxwcv** [comment] 2024-08-09 15:30
> 我现在知道问题了，请直接关闭这个问题。谢谢！只需将其替换为内存读取即可。我将改用VMMLL_readEX

Brother, how did you solve it? How do I need to change the original content
